import type { BuildingData, AABB } from '@/types/building';

export const BUILDINGS: BuildingData[] = [
  {
    id: 'about',
    name: 'About Me',
    emoji: '🏠',
    accentColor: '#4ADE80',
    position: [-20, 0, -18],
    size: { w: 7, h: 5, d: 7 },
    triggerRadius: 5.5,
    collider: { minX: -23.8, maxX: -16.2, minZ: -21.8, maxZ: -14.8 },
    doorSide: 'south',
    style: 'medieval',
  },
  {
    id: 'projects',
    name: 'Projects',
    emoji: '🏭',
    accentColor: '#60A5FA',
    position: [20, 0, -18],
    size: { w: 9, h: 6, d: 8 },
    triggerRadius: 6,
    collider: { minX: 15.7, maxX: 24.3, minZ: -22.3, maxZ: -14.3 },
    doorSide: 'south',
    style: 'industrial',
  },
  {
    id: 'skills',
    name: 'Skills',
    emoji: '📚',
    accentColor: '#FBBF24',
    position: [-20, 0, 8],
    size: { w: 7, h: 5, d: 7 },
    triggerRadius: 5.5,
    collider: { minX: -23.8, maxX: -16.2, minZ: 4.2, maxZ: 11.2 },
    doorSide: 'south',
    style: 'japanese',
  },
  {
    id: 'tools',
    name: 'Tools',
    emoji: '🔧',
    accentColor: '#FB923C',
    position: [20, 0, 8],
    size: { w: 6, h: 5, d: 6 },
    triggerRadius: 5,
    collider: { minX: 17.2, maxX: 22.8, minZ: 5.2, maxZ: 10.2 },
    doorSide: 'south',
    style: 'japanese',
  },
  {
    id: 'leadership',
    name: 'Experience',
    emoji: '🏛️',
    accentColor: '#A78BFA',
    position: [-14, 0, 28],
    size: { w: 8, h: 6, d: 7 },
    triggerRadius: 5.5,
    collider: { minX: -18.3, maxX: -9.7, minZ: 24.7, maxZ: 30.7 },
    doorSide: 'south',
    style: 'chinese',
  },
  {
    id: 'contact',
    name: 'Contact',
    emoji: '📮',
    accentColor: '#F472B6',
    position: [14, 0, 28],
    size: { w: 6, h: 5, d: 6 },
    triggerRadius: 5,
    collider: { minX: 11.2, maxX: 16.8, minZ: 25.2, maxZ: 30.2 },
    doorSide: 'south',
    style: 'medieval',
  },
];

export const ENVIRONMENT_COLLIDERS: AABB[] = [
  // Grand Monument Pagoda Base (centered at 0, -5, size 5x5)
  { minX: -2.5, maxX: 2.5, minZ: -7.5, maxZ: -2.5 },
];
