export const about = {
  name: 'Nikhil Kumar Yadav',
  title: 'CS @ RIT | 9.28 CGPA (yes, really)',
  photo: '/images/avatar.jpg',
  bio: [
    "CS undergrad at Ramaiah Institute of Technology pulling a 9.28 CGPA — which is either impressive or concerning depending on how you feel about people who actually read textbooks. I build apps, break things, fix them, and occasionally ship something that survives contact with real users.",
    "My stack spans Flutter, React, Node.js, Firebase, and whatever else the project demands. I've done Android internship research at Samsung R&D, civic tech for Smart India Hackathon, and contributed to open-source tools — all while maintaining the academic performance my parents brag about at family dinners.",
  ],
  education: [
    {
      institution: 'Ramaiah Institute of Technology',
      degree: 'B.E. Computer Science and Engineering',
      period: '2022 – 2026',
      score: 'CGPA: 9.28 / 10.00',
      courses: 'OOP, DSA, DBMS, OS, Computer Networks, Cryptography & Network Security',
    },
    {
      institution: 'Kendriya Vidyalaya AFS Guwahati',
      degree: 'XII — PCM',
      period: '2022',
      score: '93.8%',
      courses: 'Physics, Chemistry, Mathematics',
    },
  ],
  hobbies: [
    { icon: '🏋️', label: 'Gym', desc: 'Because apparently brains alone aren\'t enough.' },
    { icon: '🚴', label: 'Cycling', desc: 'Nature\'s debugging session.' },
    { icon: '🏃', label: 'Running', desc: 'Great for thinking. Terrible for the knees.' },
    { icon: '🔧', label: 'Hardware Teardowns', desc: 'If it has screws, it\'s getting opened.' },
    { icon: '⚙️', label: 'Mechanical Parts', desc: 'The beauty of things that actually make sense.' },
    { icon: '🎮', label: 'Gaming', desc: 'Done every GTA, CoD, and Hitman ever made. Professionally.' },
  ],
  games: ['GTA III, VC, SA, IV, V', 'CoD MW, MW2, MW3, Cold War, Warzone', 'Hitman (the whole franchise)', 'And yes, Minecraft — hence this portfolio.'],
  achievements: [
    '🏆 wHACKiest 2025 (MSRIT) — 2nd Runner-Up',
    '🏆 wHACKiest 2024 (MSRIT) — Top 5',
    '📐 PRMO & RMO Qualified',
    '🧠 NSTSE State Rank: 5',
    '📡 IEEE RIT — Coverage & Computer Society Member',
  ],
  currentlyBuilding: 'This 3D Minecraft portfolio (meta, I know). Also exploring ML pipelines and 3D web rendering.',
  currentlyLearning: '3D graphics (WebGL/Three.js), and how to explain what GDExtension is to non-Godot people.',
  funFacts: [
    '⚡ Has played every GTA title. Still has opinions on GTA IV physics.',
    '🔩 Will disassemble any device once. For science.',
    '🎯 NSTSE State Rank 5 — apparently competitive exams were also a thing.',
    '🌀 Diagnosed with "just one more feature" syndrome. Seeking treatment.',
  ],
  resumeUrl: '/NIK_MAIN.pdf',
};
